apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  replicas: 1
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: db
      component: mysql
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mysql
    spec:
      serviceAccount: mysql-secret-reader
      initContainers:
      - name: secret-reader
        image: amazon/aws-cli
        command: 
        - sh
        - -c
        - |
            aws secretsmanager get-secret-value --secret-id roboshop/dev/mysql_root_password \
            --query SecretString --output text | jq -r .MYSQL_ROOT_PASSWORD > /secrets/mysql-secret-reader.txt
            echo "Secret placed successfully"
            cat /secrets/mysql-secret-reader.txt # just for verification, should not do actually in prod
        volumeMounts:
        - name: mysql-secret
          mountPath: /secrets
      containers:
      - name: mysql
        image: joindevops/mysql:1.4.0
        volumeMounts:
        - name: mysql-secret
          mountPath: /secrets
      volumes:
      - name: mysql-secret
        emptyDir: {}
